fixup: assert we don't have history entries...

diff --git a/util/grub.d/10_linux_zfs.in b/util/grub.d/10_linux_zfs.in
--- a/util/grub.d/10_linux_zfs.in
+++ b/util/grub.d/10_linux_zfs.in
@@ -1005,6 +1005,12 @@ generate_grub_menu() {
                     at_least_one_entry=1
                 ;;
                 history)
+                    #
+                    # On Delphix, we don't use zsys, so we should never have history entries.
+                    #
+                    echo "Unexpected history entry encountered, aborting." >&2
+                    exit 1
+
                     # Revert to a snapshot
                     # revert system, revert system and user data and associated recovery entries
                     if [ "${last_section}" != "${section}" ]; then
