Ubuntu: add initrd-less-boot informational messages
Gbp-Pq: ubuntu-add-initrd-less-boot-messages.patch.

diff --git a/util/grub.d/10_linux.in b/util/grub.d/10_linux.in
--- a/util/grub.d/10_linux.in
+++ b/util/grub.d/10_linux.in
@@ -160,6 +160,12 @@ if [ "$vt_handoff" = 1 ]; then
 fi
 
 if [ x"$GRUB_FORCE_PARTUUID" != x ]; then
+    gettext_printf "GRUB_FORCE_PARTUUID is set, will attempt initrdless boot\n" >&2
+    cat << EOF
+#
+# GRUB_FORCE_PARTUUID is set, will attempt initrdless boot
+# Upon panic fallback to booting with initrd
+EOF
    echo "set partuuid=${GRUB_FORCE_PARTUUID}"
 fi
 
@@ -238,6 +244,8 @@ EOF
       linux_root_device_thisversion="PARTUUID=${GRUB_FORCE_PARTUUID}"
   fi
   message="$(gettext_printf "Loading initial ramdisk ...")"
+  initrdlessfail_msg="$(gettext_printf "GRUB_FORCE_PARTUUID set, initrdless boot failed. Attempting with initrd.")"
+  initrdlesstry_msg="$(gettext_printf "GRUB_FORCE_PARTUUID set, attempting initrdless boot.")"
   initrd_path=
   for i in ${initrd}; do
       initrd_path="${initrd_path} ${rel_dirname}/${i}"
@@ -249,6 +257,7 @@ EOF
   if test -n "${initrd}" && [ x"$GRUB_FORCE_PARTUUID" != x ]; then
       sed "s/^/$submenu_indentation/" << EOF
 	if [ "\${initrdfail}" = 1 ]; then
+		echo	'$(echo "$initrdlessfail_msg" | grub_quote)'
 		linux	${rel_dirname}/${basename} root=${linux_root_device_thisversion} ro ${args}
 EOF
       if [ x"$quiet_boot" = x0 ] || [ x"$type" != xsimple ]; then
@@ -259,6 +268,7 @@ EOF
       sed "s/^/$submenu_indentation/" << EOF
 		initrd	$(echo $initrd_path)
 	else
+		echo	'$(echo "$initrdlesstry_msg" | grub_quote)'
 		linux	${rel_dirname}/${basename} root=${linux_root_device_thisversion} ro ${args} panic=-1
 EOF
       if [ -n "$initrd_path_only_early" ]; then
